# k8s/mongo.yaml
apiVersion: v1
kind: Pod
metadata:
  name: mongo
  namespace: rms-dev
  labels:
    app: mongo
spec:
  containers:
    - name: mongo
      image: mongo:5.0
      ports:
        - containerPort: 27017
---
apiVersion: v1
kind: Service
metadata:
  name: mongo
  namespace: rms-dev
spec:
  selector:
    app: mongo
  ports:
    - port: 27017
