# k8s/item-service.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-service
  namespace: rms-dev
spec:
  replicas: 5
  selector:
    matchLabels:
      app: order-service
  template:
    metadata:
      labels:
        app: order-service
    spec:
      containers:
        - name: order-service
          image: ourmind/order-service:latest
          ports:
            - containerPort: 3000
          env:
            - name: MONGO_URI
              value: mongodb://mongo:27017/rms-order-db
            - name: NODE_ENV
              value: development
---
apiVersion: v1
kind: Service
metadata:
  name: order-service
  namespace: rms-dev
spec:
  selector:
    app: order-service
  ports:
    - port: 80
      targetPort: 3000
